### ISSUE TITLE
How does the parameter $rpi_version work?

### ISSUE THREAD

**Issue by josephernest** [ShorTie8/my_pi_os#1]
Let's assume `bootloader=kernel`.
Let's assume `debian_version` is _not_ set, i.e. it is **not** `ftp`.

Then all the conditions
`if [ "$debian_version" == "ftp" ] && [ "$rpi_version" == "rpi2" ]; then`
will be false, and then (I checked the whole .sh code) ....  `$rpi_version` won't be used anywhere else.

Then, how does your script know it has to build a RPi or RPi2 image?

---

Does this mean it's possible to build an image that works for both RPi and RPi2?

**Comment by ShorTie8** [comment]
"debian_version" == "ftp"  only works for a rpi2.
because a rpi is armv6 and ftp.Debian is armv7

the foundations bootloader/kernel contains both kernels for the rpi and rpi2
where as the no-kernel bootloader does not, thus the need to specify the rpi or rpi2
That is 1 of the reasons I recommend the foundations bootloader

**Comment by josephernest** [comment]
I double-checked: if `bootloader=kernel`, and   `debian_version` is **not** set to `ftp`, 
then the parameter `$rpi_version` is useless in the .sh script.   Is it correct?

## 

Then if this parameter is useless, how can your script determine if it should build an image for Rpi1 or Rpi2 ?

Then, the produced image will probably work for both RPi1 and RPi2, is it correct?

**Comment by ShorTie8** [comment]
As long as 'bootloader=kernel' it will build a image that will work on either rpi or rpi2

**Comment by josephernest** [comment]
Great!
